# -*- mode: org; fill-column:65 -*-

#+TITLE: cosmo.el
#+AUTHOR: Francesco Montanari

cosmo.el --- Cosmological Calculator

Copyright (C) 2017 Francesco Montanari [[mailto:fmnt@fmnt.info][<fmnt@fmnt.info>]]

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

* Description

  /Easily compute cosmological quantities from the Emacs text
  editor./

  This package provides a cosmological calculator for Lambda-CDM
  models. Such a framework describes a homogeneous and isotropic
  universe containing a cosmological constant (Lambda) and a Cold
  Dark Matter (CDM) component, besides ordinary species. The
  model is characterized by the following parameters:

  - H_0 :: Hubble parameter (expansion rate) today.
  - Omega_m0 :: Matter density parameter today.
  - Omega_Lambda :: Cosmological constant density parameter.
  - Omega_r0 :: Relativistic species (e.g., photons plus
                neutrinos) density parameter today.
  - Omega_k0 :: Curvature density parameter today. This
                parameter is derived from the others above
                according to Friedmann's equation
                =Omega_m0 + Omega_Lambda + Omega_r0 + Omega_k0 = 1=.

  All cosmological quantities are computed at a given redshift
  value:

  - redshift :: Gravitational redshift of photons frequency due to the
                expansion of the Universe.

  Definitions follow Hogg (1999) [[[https://arxiv.org/abs/astro-ph/9905116][arXiv:astro-ph/9905116]]]. The
  =cosmo-pedia= command is based on [[http://fiteoweb.unige.ch/~durrer/Book.html][Durrer (2008)]]. The
  =cosmo-calculator= command is based on Gnuastro =astcosmiccal=
  program (v0.2).

* Download

  The source code can be downloaded from the [[https://gitlab.com/montanari/cosmo-el][git repository page]].

  Alternatively, the git repository can be cloned:
  #+BEGIN_SRC shell
  git clone git@gitlab.com:montanari/cosmo-el.git
  #+END_SRC

* Installation

  This program is meant to work with the [[https://www.gnu.org/software/emacs/][Emacs]] text editor. Copy
  the =cosmo.el= file into a sub-folder under your Emacs
  configuration directory. (In general this directory can be
  accessed from Emacs, independently from the operating system,
  by typing the command =C-x C-f ~/.emacs.d/=.) E.g., on GNU
  systems:

  #+BEGIN_SRC shell
  mkdir ~/.emacs.d/cosmo-el
  cp cosmo.el ~/.emacs.d/cosmo-el
  #+END_SRC

  Open your Emacs configuration file (e.g., =~/.emacs= on GNU
  systems), and add the following lines:

  #+BEGIN_SRC emacs-lisp
  ;; Cosmological calculator
  (add-to-list 'load-path "~/.emacs.d/cosmo-el/")
  (require 'cosmo)
  #+END_SRC

* Usage

  Open Emacs and type =M-x cosmo-command= (the notation =M-x=
  means that the =ALT= and =x= keys should be pressed
  simultaneously), where the =command= name varies depending on
  the desired computation:

  # List all interactive commands:
  #   (apropos-command "cosmo-")

  - cosmo-angular-diameter-distance :: Display angular diameter
       distance in mini-buffer.

  - cosmo-calculator :: Compute cosmology and display summary
       table in a new buffer. The following illustrates a
       possible output:
       #+BEGIN_EXAMPLE
       Cosmology calculator.

       Input Parameters
       ----------------
       - Redshift:                       	0.1
       - Hubble constant, now [km/s/Mpc]:	70.0
       - Matter fractional density, now: 	0.3
       <...>

       Cosmography at required redshift
       -------------------------------
       - Hubble parameter [km/s/Mpc]:	73.39325582095401
       <...>
       #+END_EXAMPLE

  - cosmo-hubble :: Display Hubble parameter in mini-buffer.

  - cosmo-hubble-distance :: Display Hubble distance c/H0 [Mpc]
       in mini-buffer.

  - cosmo-hubble-time :: Display Hubble distance 1/H0 [Gyr] in
       mini-buffer.

  - cosmo-los-comoving-distance :: Display line-of-sight comoving
       distance in mini-buffer.

  - cosmo-luminosity-distance :: Display luminosity distance in
       mini-buffer.

  - cosmo-pedia :: Display a reference to basic cosmological
                   definitions.

  - cosmo-set-params :: Change the values of cosmological parameters.

  - cosmo-transverse-comoving-distance :: Display transverse
       comoving distance in mini-buffer.

  Use the command =M-x customize= to set variables related to
  internal implementation details (e.g., the precision of
  numerical integrals), under the =Cosmo= group.

* Support

  Bugs and issues are tracked through the [[https://gitlab.com/montanari/cosmo-el][git repository page]]. Please
  see [[http://www.chiark.greenend.org.uk/~sgtatham/bugs.html][this page]] about how to report bugs effectively.

* Contributing

  Contributions can be submitted as patches. See [[http://orgmode.org/worg/org-contribute.html#patches][this page]] for an
  example of good patches contributions.

  More substantial contributions should proceed through git
  [[https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows][Integration-Manager Workflow]]. In short: fork the repository, do
  the changes on a new branch (the master branch should only be
  used to pull updates from the original git remote onto your
  personal repository) and notify via the issue tracker or email
  about the modifications.
